sudo: true
language: node_js
node_js:
  - "lts/*"
  - "6"
services:
  - docker
before_install:
  - docker pull rabbitmq:3.6-management
  - docker run -d -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_VHOST=test -e RABBITMQ_DEFAULT_USER=test -e RABBITMQ_DEFAULT_PASS=test rabbitmq:3.6-management
  - sleep 5
script:
  - npm run report
after_script:
  - "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"