name: Publish Docs

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DOCS_KEY }}
          aws-secret-access-key: ${{ secrets.DOCS_SECRET }}
          aws-region: us-east-1

      - name: Copy Docs
        run: aws s3 cp ./README.md s3://okanjo-docs/okanjo-app-queue/ --acl public-read --content-type "text/plain; charset=utf-8" --content-encoding text
